const TITLE = 'Auth';
const USERNAME_TEXT_FIELD_LABEL = 'Username';
const PASSWORD_TEXT_FIELD_LABEL = 'Password';
const LOGIN_SUBMIT_BUTTON_TEXT = 'Login';
const SUCCESS_MESSAGE = 'You were successfully logged in';

export { TITLE, USERNAME_TEXT_FIELD_LABEL, PASSWORD_TEXT_FIELD_LABEL, LOGIN_SUBMIT_BUTTON_TEXT, SUCCESS_MESSAGE };
